#include <stdio.h>

/**
 * Project Euler Problem 2:
 *   Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *   By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *   
 *   Answer: 4613732
 */

int main()
{  
  // passively and iteratively compute fibonacci numbers
  // under 4,000,000; add to the sum if divisible by 2
  unsigned int sum = 0, i = 1, j = 1, n;
  while(n < 4000000)
  {
    n = i + j; i = j; j = n; // compute the next fibonacci number
    if(n % 2 == 0) sum += n; // add to sum if applicable
  }   
  printf("%d\n", sum);
}
